### Get all courses
GET http://localhost:8080/api/courses

### Get courses by level (RequestParam)
GET http://localhost:8080/api/courses?level=BEGINNER

### Get course by id (PathVariable)
GET http://localhost:8080/api/courses/1

### Not found example
GET http://localhost:8080/api/courses/999
